// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdgjUDJH7QwGqO6Zt6eE5mNKuxgZoREg8',
    appId: '1:307909534155:web:bea60b19f8ac652345d64e',
    messagingSenderId: '307909534155',
    projectId: 'mark-my-attendance-675a5',
    authDomain: 'mark-my-attendance-675a5.firebaseapp.com',
    storageBucket: 'mark-my-attendance-675a5.appspot.com',
    measurementId: 'G-RK8W2EK2PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3t5xhkV2r7sN9gOI_5cA9TkplJQsT58',
    appId: '1:307909534155:android:15aec261e4a1adc245d64e',
    messagingSenderId: '307909534155',
    projectId: 'mark-my-attendance-675a5',
    storageBucket: 'mark-my-attendance-675a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm1SO2yH19T_16I5tEQGjAH9-mtEfDrMw',
    appId: '1:307909534155:ios:aab38c02a078bb5745d64e',
    messagingSenderId: '307909534155',
    projectId: 'mark-my-attendance-675a5',
    storageBucket: 'mark-my-attendance-675a5.appspot.com',
    iosClientId: '307909534155-o5go06gjkp6a336h7cc0m31204sdb1kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.markMyAttendance',
  );
}
